In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
data=pd.read_excel

In [ ]:
#1. Customers own their connection

In [ ]:
data.head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95      1889.50     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [ ]:
data['gender'].value_counts()

Male      3555
Female    3488
Name: gender, dtype: int64

In [ ]:
data

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0     7590-VHVEG  Female              0  ...          29.85        29.85     No
1     5575-GNVDE    Male              0  ...          56.95      1889.50     No
2     3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3     7795-CFOCW    Male              0  ...          42.30      1840.75     No
4     9237-HQITU  Female              0  ...          70.70       151.65    Yes
...          ...     ...            ...  ...            ...          ...    ...
7038  6840-RESVB    Male              0  ...          84.80      1990.50     No
7039  2234-XADUH  Female              0  ...         103.20      7362.90     No
7040  4801-JZAZL  Female              0  ...          29.60       346.45     No
7041  8361-LTMKD    Male              1  ...          74.40       306.60    Yes
7042  3186-AJIEK    Male              0  ...         105.65      6844.50     No

[7043 rows x 21 columns]

In [ ]:
data1 = data[data["Churn"]=="No"]
data1

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0     7590-VHVEG  Female              0  ...          29.85        29.85     No
1     5575-GNVDE    Male              0  ...          56.95      1889.50     No
3     7795-CFOCW    Male              0  ...          42.30      1840.75     No
6     1452-KIOVK    Male              0  ...          89.10      1949.40     No
7     6713-OKOMC  Female              0  ...          29.75       301.90     No
...          ...     ...            ...  ...            ...          ...    ...
7037  2569-WGERO  Female              0  ...          21.15      1419.40     No
7038  6840-RESVB    Male              0  ...          84.80      1990.50     No
7039  2234-XADUH  Female              0  ...         103.20      7362.90     No
7040  4801-JZAZL  Female              0  ...          29.60       346.45     No
7042  3186-AJIEK    Male              0  ...         105.65      6844.50     No

[5174 rows x 21 columns]

In [ ]:
data1["gender"].value_counts()

Male      2625
Female    2549
Name: gender, dtype: int64

In [ ]:
data1["SeniorCitizen"].value_counts()

0    4508
1     666
Name: SeniorCitizen, dtype: int64

In [ ]:
#2. Customer left their connection

In [ ]:
data2= data[data["Churn"]=="Yes"]
data2

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
2     3668-QPYBK    Male              0  ...          53.85       108.15    Yes
4     9237-HQITU  Female              0  ...          70.70       151.65    Yes
5     9305-CDSKC  Female              0  ...          99.65       820.50    Yes
8     7892-POOKP  Female              0  ...         104.80      3046.05    Yes
13    0280-XJGEX    Male              0  ...         103.70      5036.30    Yes
...          ...     ...            ...  ...            ...          ...    ...
7021  1699-HPSBG    Male              0  ...          59.80       727.80    Yes
7026  8775-CEBBJ  Female              0  ...          44.20       403.35    Yes
7032  6894-LFHLY    Male              1  ...          75.75        75.75    Yes
7034  0639-TSIQW  Female              0  ...         102.95      6886.25    Yes
7041  8361-LTMKD    Male              1  ...          74.40       306.60    Yes

[1869 rows x 21 columns]

In [ ]:
data2["gender"].value_counts()

Female    939
Male      930
Name: gender, dtype: int64

In [ ]:
data2["SeniorCitizen"].value_counts()

0    1393
1     476
Name: SeniorCitizen, dtype: int64

In [ ]:
#3. Payment Method

In [ ]:
data["PaymentMethod"].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [ ]:
data['Contract'].unique()

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [ ]:
#Preference payment method based on churn

In [ ]:
data1["PaymentMethod"].value_counts(normalize=True)*100